web:
  build: .
  command: 'bash -c ''bin/rake db:migrate && bundle exec puma -C config/puma.rb'''
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
    RAILS_ENV: development
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/usr/src/app'
herokuPostgresql:
  image: postgres
  volumes:
    - pgdata:/var/lib/postgresql/data/
